-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 11:18:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ihakula_wechat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ihakula_wechat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ihakula_wechat` DEFAULT CHARACTER SET utf8 ;
USE `ihakula_wechat` ;

-- -----------------------------------------------------
-- Table `ihakula_wechat`.`wx_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ihakula_wechat`.`wx_user` (
  `union_id` VARCHAR(100) NOT NULL,
  `index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickName` VARCHAR(45) NULL,
  `gender` INT NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `avatarUrl` VARCHAR(200) NULL,
  `create_time` DATETIME NULL,
  `activity_time` DATETIME NULL,
  PRIMARY KEY (`union_id`),
  UNIQUE INDEX `id_UNIQUE` (`index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ihakula_wechat`.`wx_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ihakula_wechat`.`wx_app` (
  `app_id` VARCHAR(100) NOT NULL,
  `index` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `app_secret` VARCHAR(100) NULL,
  `app_name` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`app_id`),
  UNIQUE INDEX `app_id_UNIQUE` (`app_id` ASC),
  UNIQUE INDEX `index_UNIQUE` (`index` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ihakula_wechat`.`wx_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ihakula_wechat`.`wx_token` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(128) NULL,
  `open_id` VARCHAR(128) NULL,
  `session_key` VARCHAR(128) NULL,
  `valid_time` DATETIME NULL,
  `wx_app_id` VARCHAR(100) NOT NULL,
  `wx_user_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_wx_token_wx_app1_idx` (`wx_app_id` ASC),
  UNIQUE INDEX `wx_app_app_id_UNIQUE` (`wx_app_id` ASC),
  INDEX `fk_wx_token_wx_user1_idx` (`wx_user_id` ASC),
  CONSTRAINT `fk_wx_token_wx_app1`
    FOREIGN KEY (`wx_app_id`)
    REFERENCES `ihakula_wechat`.`wx_app` (`app_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wx_token_wx_user1`
    FOREIGN KEY (`wx_user_id`)
    REFERENCES `ihakula_wechat`.`wx_user` (`union_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
